import type { Question } from './types';

export const questions: Question[] = [
  {
    id: 1,
    text: 'What is the SI unit of force?',
    type: 'MCQ',
    subject: 'Physics',
    chapter: 'Laws of Motion',
    difficulty: 'Easy',
    options: ['Joule', 'Watt', 'Newton', 'Pascal'],
    correctAnswer: 'Newton',
  },
  {
    id: 2,
    text: 'A body of mass 5 kg is moving with a velocity of 10 m/s. What is its kinetic energy?',
    type: 'MCQ',
    subject: 'Physics',
    chapter: 'Work, Energy and Power',
    difficulty: 'Easy',
    options: ['250 J', '50 J', '500 J', '100 J'],
    correctAnswer: '250 J',
  },
  {
    id: 3,
    text: 'According to the diagram, what is the equivalent resistance between points A and B if all resistors are 10Ω?',
    image: 'https://picsum.photos/seed/circuits/600/400',
    type: 'MCQ',
    subject: 'Physics',
    chapter: 'Current Electricity',
    difficulty: 'Medium',
    options: ['10 Ω', '20 Ω', '30 Ω', '40 Ω'],
    correctAnswer: '10 Ω',
  },
  {
    id: 4,
    text: 'Explain Newton\'s Second Law of Motion in your own words.',
    type: 'Subjective',
    subject: 'Physics',
    chapter: 'Laws of Motion',
    difficulty: 'Medium',
    correctAnswer: 'Newton\'s Second Law of Motion states that the rate of change of momentum of a body is directly proportional to the force applied, and this change in momentum takes place in the direction of the applied force. It is mathematically expressed as F = ma, where F is force, m is mass, and a is acceleration.',
  },
  {
    id: 5,
    text: 'What is the principle of conservation of energy?',
    type: 'MCQ',
    subject: 'Physics',
    chapter: 'Work, Energy and Power',
    difficulty: 'Medium',
    options: [
        'Energy can be created but not destroyed',
        'Energy can be destroyed but not created',
        'Energy can neither be created nor destroyed, only transformed',
        'Energy is always constant in a closed system'
    ],
    correctAnswer: 'Energy can neither be created nor destroyed, only transformed',
  },
  {
    id: 6,
    text: 'Which of the following is a vector quantity?',
    type: 'MCQ',
    subject: 'Physics',
    chapter: 'Vectors',
    difficulty: 'Easy',
    options: ['Speed', 'Distance', 'Mass', 'Velocity'],
    correctAnswer: 'Velocity',
  },
    {
    id: 7,
    text: 'An object is dropped from a height of 20m. What is its velocity just before it hits the ground? (Assume g = 9.8 m/s² and neglect air resistance)',
    type: 'MCQ',
    subject: 'Physics',
    chapter: 'Motion in a Straight Line',
    difficulty: 'Hard',
    options: ['19.8 m/s', '196 m/s', '14 m/s', '20 m/s'],
    correctAnswer: '19.8 m/s',
  },
];
